EPAM/EPAM.WebClient/Controllers/AuthorController.cs
using EPAM.Model;
using EPAM.Model.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EPAM.WebClient.Controllers
{
    public class AuthorController : Controller
    {
        #region FindJobs
        public void InitJobsPartial(List<Guid> jobIds, int page)
        {
            if (jobIds.Count == 0)
                ViewBag.HasJobs = false;
            else
            {
                ViewBag.HasJobs = true;

                ViewBag.Pages = new List<int>();
                for (int i = 0; i < (int)Math.Ceiling(jobIds.Count / 10.0); i++)
                {
                    ViewBag.Pages.Add(i + 1);
                }
                ViewBag.CurrentPage = page;
                ViewBag.Jobs = new List<Job>();
                for (int i = (page - 1) * 10; i < page * 10 && i < jobIds.Count; i++)
                {
                    ViewBag.Jobs.Add(JobRepository.Instance.GetItemById(jobIds[i]));
                }
            }
        }

        public ActionResult FindJobs()
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            ViewBag.JobCategories = JobCategoryRepository.Instance.GetAllItems().OrderBy(i => i.Name);

            JobFilter jobFilter = new JobFilter();
            List<Guid> jobIds = JobRepository.Instance.GetFilterJobIdsDirectly(jobFilter);
            InitJobsPartial(jobIds, 1);

            return View(jobFilter);
        }

        [HttpPost]
        public PartialViewResult GetJobSubcategories(Guid JobCategoryId)
        {
            if (Session["PersonId"] == null)
                return null;

            List<JobSubcategory> jobSubcategories = JobSubcategoryRepository.Instance.GetCategorySubcategories(JobCategoryRepository.Instance.GetItemById(JobCategoryId));
            ViewBag.JobSubcategories = jobSubcategories.OrderBy(i => i.Name);
            ViewBag.HasItems = jobSubcategories.Count > 0;
            return PartialView("_JobSubcategory");
        }

        [HttpPost]
        public void SaveFilter(JobFilter jobFilter)
        {
            if (Session["PersonId"] == null)
                return;

            jobFilter.AuthorId = (Guid)Session["PersonId"];
            JobFilterRepository.Instance.SetItem(jobFilter);
        }

        [HttpPost]
        public void RemoveFilter(Guid jobFilterId)
        {
            if (Session["PersonId"] == null)
                return;

            JobFilterRepository.Instance.RemoveItem(jobFilterId);
        }

        [HttpPost]
        public PartialViewResult GetSavedFilters()
        {
            if (Session["PersonId"] == null)
                return null;

            Author author = AuthorRepository.Instance.GetItemById((Guid)Session["PersonId"]);
            List<JobFilter> filters = JobFilterRepository.Instance.GetAuthorSavedJobFilters(author);
            if (filters.Count == 0)
                ViewBag.HasSavedFilters = false;
            else
            {
                ViewBag.HasSavedFilters = true;
                ViewBag.SavedFilters = filters;
            }
            return PartialView("_SavedFilters");
        }

        [HttpPost]
        public PartialViewResult GetJobsByFilter(JobFilter jobFilter, int page = 1)
        {
            if (Session["PersonId"] == null)
                return null;

            List<Guid> jobIds = JobRepository.Instance.GetFilterJobIdsDirectly(jobFilter);
            InitJobsPartial(jobIds, page);
            
            return PartialView("_Jobs", jobFilter);
        }

        [HttpPost]
        public PartialViewResult GetJobsByFilterId(Guid jobFilterId)
        {
            if (Session["PersonId"] == null)
                return null;

            List<Guid> jobIds = JobRepository.Instance.GetFilterJobIds(jobFilterId);
            InitJobsPartial(jobIds, 1);
            return PartialView("_Jobs", JobFilterRepository.Instance.GetItemById(jobFilterId));
        }

        [HttpPost]
        public void SaveJob(Guid jobId)
        {
            AuthorSavedJob asj = new AuthorSavedJob();
            asj.AuthorId = (Guid)Session["PersonId"];
            asj.JobId = jobId;
            AuthorSavedJobRepository.Instance.SetItem(asj);
        }

        [HttpPost]
        public void UnSaveJob(Guid jobId)
        {
            Author author = AuthorRepository.Instance.GetItemById((Guid)Session["PersonId"]);
            List<AuthorSavedJob> list = AuthorSavedJobRepository.Instance.GetAuthorSavedJobs(author);
            foreach (var item in list)
                if (item.JobId.Equals(jobId))
                    AuthorSavedJobRepository.Instance.RemoveItem(item);
        }
        #endregion

        #region SavedJobs
        public ActionResult SavedJobs()
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            Author author = AuthorRepository.Instance.GetItemById((Guid)Session["PersonId"]);
            ViewBag.Jobs = JobRepository.Instance.GetAuthorSavedJobs(author);
            ViewBag.HasJobs = Enumerable.Count(ViewBag.Jobs) > 0;

            return View();
        }
        #endregion

        #region MyJobs
        public ActionResult MyJobs()
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            Author author = AuthorRepository.Instance.GetItemById((Guid)Session["PersonId"]);
            ViewBag.OngoingJobs = JobRepository.Instance.GetAuthorOngoingJobs(author).OrderByDescending(i => i.PostedDate);
            ViewBag.HasOngoingJobs = Enumerable.Count(ViewBag.OngoingJobs) > 0;

            ViewBag.PastJobs = JobRepository.Instance.GetAuthorPastJobs(author);
            ViewBag.HasPastJobs = Enumerable.Count(ViewBag.PastJobs) > 0;

            return View();
        }

        public bool SubmitJob(Guid jobId)
        {
            if (Session["PersonId"] == null)
                return false;

            Job job = JobRepository.Instance.GetItemById(jobId);
            job.IsClosed = true;
            JobRepository.Instance.UpdateItem(job);

            return true;
        }
        #endregion

        #region JobOverview
        public ActionResult JobOverview(Guid? jobId = null)
        {
            if (Session["PersonId"] == null || jobId == null)
                return Redirect(ControllersLibrary.LogInPage);

            Guid authorId = (Guid)Session["PersonId"];
            Job job = JobRepository.Instance.GetItemById((Guid)jobId);
            ViewBag.AlreadyApplied = Enumerable.Count(job.Applications.Where(a => a.AuthorId == authorId)) > 0;

            return View(JobRepository.Instance.GetItemById((Guid)jobId));
        }
        #endregion

        #region JobApply
        public ActionResult JobApply(Guid? jobId = null)
        {
            if (Session["PersonId"] == null || jobId == null)
                return Redirect(ControllersLibrary.LogInPage);

            return View(JobRepository.Instance.GetItemById((Guid)jobId));
        }

        public bool SaveApply(List<Answer> answers, Guid jobId)
        {
            if (Session["PersonId"] == null)
                return false;

            Application application = new Application();
            application.AuthorId = (Guid)Session["PersonId"];
            application.JobId = jobId;
            ApplicationRepository.Instance.SetItem(application);

            foreach(var item in answers)
            {
                item.ApplicationId = application.Id;
                AnswerRepository.Instance.SetItem(item);
            }
            return true;
        }
        #endregion

        #region MyApplications
        public ActionResult MyApplications()
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            Author author = AuthorRepository.Instance.GetItemById((Guid)Session["PersonId"]);
            ViewBag.OngoingApplications = ApplicationRepository.Instance.GetAuthorOngoingApplications(author);
            ViewBag.HasOngoingApplications = Enumerable.Count(ViewBag.OngoingApplications) > 0;

            ViewBag.PastApplications = ApplicationRepository.Instance.GetAuthorPastApplications(author);
            ViewBag.HasPastApplications = Enumerable.Count(ViewBag.PastApplications) > 0;

            return View();
        }
        #endregion

        #region ApplicationOverview
        public ActionResult ApplicationOverview(Guid? applicationId = null)
        {
            if (Session["PersonId"] == null || applicationId == null)
                return Redirect(ControllersLibrary.LogInPage);

            return View(ApplicationRepository.Instance.GetItemById((Guid)applicationId));
        }
        #endregion

        #region Talks
        public ActionResult Talks()
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            return View();
        }
        #endregion

        #region Profile
        public ActionResult Profile(Guid? id = null)
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            Guid personId = (Guid)Session["PersonId"];

            if (id == null)
                return null;

            ViewBag.TimeZones = TimeZoneRepository.Instance.GetAllItems().OrderBy(i => i.Title);
            ViewBag.IsOwner = id.Equals(personId);
            Author author = AuthorRepository.Instance.GetItemById((Guid)id);

            return View(author);
        }

        [HttpPost]
        public PartialViewResult SaveAuthor(Author author)
        {
            if (Session["PersonId"] == null)
                return null;

            Author newAuthor = AuthorRepository.Instance.GetItemById((Guid)Session["PersonId"]);
            newAuthor.HourRate = author.HourRate;

EPAM/EPAM.WebClient/Views/Author/ApplicationOverview.cshtml
@model EPAM.Model.Application

@{
    ViewBag.Title = "ApplicationOverview";
    ViewBag.Menu = 0;
}

@section Links{
    @Styles.Render("~/Content/Author/ApplicationOverview.css")
}

@section FirstMenuBar{
    @Html.Partial("FirstMenuBar")
}

@section SecondMenuBar{
    @Html.Partial("JobsMenuBar")
}

<div id="workSpace">
    <h1>Application Overview</h1>
    <div id="info">
        @Html.ActionLink(Model.Job.Title, "JobOverview", "Author", new { jobId = Model.Job.Id }, null)
        <h3>@Model.Job.ShortDescription</h3>
    </div>
    <h1 id="questionsTitle">Questions:</h1>
    <form method="post" action="@Url.Action("ApproveApplication")">
        <input type="hidden" name="applicationId" value="@Model.Id" />
        <div id="questions">
            @foreach (var item in @Model.Answers)
            {
                <h3>@item.Question.Text</h3>
                <h4>@item.Text</h4>
            }
        </div>
    </form>
</div>

EPAM/EPAM.WebClient/Views/Author/Applications.cshtml
@{
    ViewBag.Title = "Applications";
    ViewBag.Menu = 0;
    ViewBag.Menu2 = 3;
}

@section FirstMenuBar{
    @Html.Partial("FirstMenuBar")
}

@section SecondMenuBar{
    @Html.Partial("JobsMenuBar")
}

<h2>Applications - @Session["PersonId"]</h2>

EPAM/EPAM.WebClient/Views/Author/FindJobs.cshtml
@model EPAM.Model.JobFilter

@{
    ViewBag.Title = "FindJobs";
    ViewBag.Menu = 0;
    ViewBag.Menu2 = 0;
}

@section Links{
    @Styles.Render("~/Content/Author/FindJobs.css")
}

@section FirstMenuBar{
    @Html.Partial("FirstMenuBar")
}

@section SecondMenuBar{
    @Html.Partial("JobsMenuBar")
}

<div id="bar">
    <ul>
        <li><a href="#filter">Filter</a></li>
        <li><a href="#savedFilters">Saved filters</a></li>
    </ul>
    <form id="updateFilterForm" action="~/Author/FindJobs">
        <div id="filter">
            <h2>Filter</h2>
            <input type="text" name="SearchString" placeholder="Search string" value="@Model.SearchString" />
            <select id="categories" name="JobCategoryId">
                <option value="@Guid.Empty">Job category</option>
                @foreach (var item in ViewBag.JobCategories)
                {
                    <option value="@item.Id">@item.Name</option>
                }
            </select>
            <div id="jobSubcategory">@Html.Partial("_JobSubcategory")</div>
            <h3>Budget:</h3>
            <div id="slider"></div>
            <input id="min" type="text" readonly name="BudgetMin" placeholder="BudgetMin" value="@Model.BudgetMin" />
            <input id="max" type="text" readonly name="BudgetMax" placeholder="BudgetMax" value="@Model.BudgetMax" />
            <input id="datetimepicker" type="text" name="DeadlineAfter" placeholder="Deadline after"
                   value="@((Model.DeadlineAfter != DateTime.MinValue) ?  @String.Format("{0:dd.MM.yyyy HH:mm}", Model.DeadlineAfter) : "")" />
            <div id="save">
                <input id="saveAs" type="button" value="Save as" />
                <input id="saveTitle" type="text" name="Title" placeholder="Title" />
            </div>
            <div id="update">
                <input id="update" type="button" value="Update" />
            </div>
        </div>
    </form>
    <div id="savedFilters"></div>
</div>
<div id="jobs">@Html.Partial("_Jobs", Model)</div>
<script>
    $(function () {
        //Page event
        function pageEvent() {
            $('#pages input[type=button]').click(function () {
                $('#page').val($(this).val());
                $.ajax({
                    url: '@Url.Action("GetJobsByFilter")',
                    data: $('#filterForm').serializeArray(),
                    type: 'POST',
                    success: function (data) {
                        $('#jobs').html(data);
                        pageEvent();
                    }
                });
            });
        }

        //Save job
        function saveEvent() {
            $('div[id^="jobPost"]').each(function () {
                var id = $(this).find('#info > input').val();

                $(this).find('#saveButton > input').click(function () {
                    if ($(this).hasClass("pressed")) {
                        $.ajax({
                            url: '@Url.Action("UnSaveJob")',
                            data: { jobId: id },
                            type: 'POST',
                            success: function () {
                            }
                        });
                        $(this).removeClass("pressed");
                    }
                    else {
                        $.ajax({
                            url: '@Url.Action("SaveJob")',
                            data: { jobId: id },
                            type: 'POST',
                            success: function () {
                            }
                        });
                        $(this).addClass("pressed");
                    }
                });
            });
        }

        //Set tabs
        $('#bar').tabs({
            activate: function (event, ui) {
                if ($('#bar').tabs('option', 'active') == 1) {
                    $.ajax({
                        url: '@Url.Action("GetSavedFilters")',
                        type: 'POST',
                        success: function (data) {
                            $('#savedFilters').html(data);

                            $('div[id^=jobFilter]').each(function () {
                                var div = $(this);

                                div.find('h4').click(function () {
                                    $.ajax({
                                        url: '@Url.Action("GetJobsByFilterId")',
                                        data: { jobFilterId: div.find('input').val() },
                                        type: 'POST',
                                        success: function (data) {
                                            $('#jobs').html(data);
                                            pageEvent();
                                            saveEvent();
                                        }
                                    });
                                });

                                div.find('span').click(function () {
                                    $.ajax({
                                        url: '@Url.Action("RemoveFilter")',
                                        data: { jobFilterId: div.find('input').val() },
                                        type: 'POST',
                                        success: function () {
                                            div.remove();
                                            if ($('#savedFilters').children().length == 0) {
                                                $('#bar').tabs('option', 'active', 0);
                                            }
                                        }
                                    });
                                });
                            });
                        }
                    });
                }
            }
        });

        //Select subcategories
        $('select#categories').change(function () {
            var id = $(this).val();

            $.ajax({
                url: '@Url.Action("GetJobSubcategories")',
                data: { JobCategoryId: id },
                type: 'POST',
                success: function (data) {
                    $('#jobSubcategory').html(data);
                }
            });
        });

        //Config budget slider
        var values = [0, 50, 100, 500, 1000, 5000, 10000, 50000, 100000];
        $('#slider').slider({
            range: true,
            min: 0,
            max: values.length - 1,
            values: [0, values.length - 1],
            slide: function (event, ui) {
                $('#min').val(values[ui.values[0]]);
                $('#max').val(values[ui.values[1]]);
            }
        });

        //Config datetimepicker
        $('#datetimepicker').datetimepicker({
            dayOfWeekStart: 1,
            lang: 'en',
            format: 'd.m.Y H:i',
            defaultTime: '0:00',
            minDate: '@DateTime.Today.ToShortDateString()',
            timepickerScrollbar: false
        });

        //Scroll div#bar
        $(document).scroll(function () {
            if ($(document).scrollTop() > 250) {
                $('#bar').addClass("fixed");
            }
            else {
                $('#bar').removeClass("fixed");
            }
        });

        //Call page event
        pageEvent();

        //Save filter
        $('#saveAs').click(function () {
            $.ajax({
                url: '@Url.Action("SaveFilter")',
                data: $('#updateFilterForm').serializeArray(),
                type: 'POST',
                success: function () {
                    $('#saveTitle').val("");
                }
            });
            $('#bar').tabs('option', 'active', 1);
        });

        //Call save event()
        saveEvent();

        //Update
        $('#update').click(function () {
            $.ajax({
                url: '@Url.Action("GetJobsByFilter")',
                data: $('#updateFilterForm').serializeArray(),
                type: 'POST',
                success: function (data) {
                    $('#jobs').html(data);
                    pageEvent();
                    saveEvent();
                }
            });
        });
    });
</script>

EPAM/EPAM.WebClient/Views/Author/FirstMenuBar.cshtml
<ul id="menu-header" class="menu">
    <li class="@(ViewBag.Menu == 0 ? "selected" : "")">@Html.ActionLink("Jobs", "FindJobs", "Author")</li>
    <li class="@(ViewBag.Menu == 1 ? "selected" : "")">@Html.ActionLink("Talks", "Talks", "Author")</li>
    <li class="@(ViewBag.Menu == 2 ? "selected" : "")">@Html.ActionLink("Profile", "Profile", "Author", new { id = Session["PersonId"]}, null)</li>
</ul>

EPAM/EPAM.WebClient/Views/Author/JobOverview.cshtml
@model EPAM.Model.Job

@{
    ViewBag.Title = "JobOverview";
    ViewBag.Menu = 0;

    string Skills = string.Join(", ", Model.Skills.Select(s => s.Title));
    int num = 1;
    string Questions = num++ + ") " + string.Join("\n" + num++ + ") ", Model.Questions.Select(q => q.Text));
}

@section Links{
    @Styles.Render("~/Content/Author/JobOverview.css")
}

@section FirstMenuBar{
    @Html.Partial("FirstMenuBar")
}

@section SecondMenuBar{
    @Html.Partial("JobsMenuBar")
}

<h1>Job Overview</h1>
<div id="applyDiv">
    @if (Model.Author != null)
    {
        <div>
            <h2>Job is closed</h2>
        </div>
    }
    else
    {
        if (ViewBag.AlreadyApplied)
        {
            <div>
                <h2>Already applied</h2>
            </div>
        }
        else
        {
            <div>
                @Html.ActionLink("Apply", "JobApply", "Author", new { jobId = Model.Id }, new { @class = "button" })
            </div>
        }
        <div id="applyInfo">
            <h2>Applications: @Enumerable.Count(Model.Applications.Where(i => i.IsClosed == false))</h2>
        </div>
    }
    
</div>
<div id="workSpace">
    <h1 id="title">@Model.Title</h1>
    <div id="info">
        <h3>@Model.JobCategory.Name, @Model.JobSubcategory.Name
            Skills: @Skills
        </h3>
        <h3>Deadline - @Model.Deadline, Budget - @Model.Budget$</h3>
    </div>
    <h1 id="descTitle">Description</h1>
    <div id="desc"><h4>@Model.Description</h4></div>
    <h1 id="questionsTitle">Questions:</h1>
    <div id="questions"><h3>@Questions</h3></div>
</div>

EPAM/EPAM.WebClient/Views/Author/MyApplications.cshtml
@{
    ViewBag.Title = "MyApplications";
    ViewBag.Menu = 0;
    ViewBag.Menu2 = 3;
}

@section Links{
    @Styles.Render("~/Content/Author/MyApplications.css")
}

@section FirstMenuBar{
    @Html.Partial("FirstMenuBar")
}

@section SecondMenuBar{
    @Html.Partial("JobsMenuBar")
}

<div id="accordion">
    <h1>Ongoing Applications</h1>
    <div>
        @if (ViewBag.HasOngoingApplications)
        {
            foreach (EPAM.Model.Application item in ViewBag.OngoingApplications)
            {
                <div id="applicationPost">
                    <div>
                        <input type="hidden" name="applicationId" value="@item.Id" />
                        @Html.ActionLink(item.Job.Title, "ApplicationOverview", "Author", new { applicationId = item.Id }, null)
                        <h5>@item.Job.ShortDescription</h5>
                    </div>
                </div>
            }
        }
        else
        {
            <h3>No Ongoing Applications</h3>
        }
    </div>
    <h1>Past Applications</h1>
    <div>
        @if (ViewBag.HasPastApplications)
        {
            foreach (EPAM.Model.Application item in ViewBag.PastApplications)
            {
                <div id="applicationPost">
                    <div>
                        <input type="hidden" name="applicationId" value="@item.Id" />
                        @Html.ActionLink(item.Job.Title, "ApplicationOverview", "Author", new { applicationId = item.Id }, null)
                        <h5>@item.Job.ShortDescription</h5>
                    </div>
                </div>
            }
        }
        else
        {
            <h3>No Past Applications</h3>
        }
    </div>
</div>

<script>
    $(function () {
        //Accordion
        $('#accordion').accordion({
            collapsible: true,
            heightStyle: "content",

            beforeActivate: function (event, ui) {
                // The accordion believes a panel is being opened
                if (ui.newHeader[0]) {
                    var currHeader = ui.newHeader;
                    var currContent = currHeader.next('.ui-accordion-content');
                    // The accordion believes a panel is being closed
                } else {
                    var currHeader = ui.oldHeader;
                    var currContent = currHeader.next('.ui-accordion-content');
                }
                // Since we've changed the default behavior, this detects the actual status
                var isPanelSelected = currHeader.attr('aria-selected') == 'true';

                // Toggle the panel's header
                currHeader.toggleClass('ui-corner-all', isPanelSelected).toggleClass('accordion-header-active ui-state-active ui-corner-top', !isPanelSelected).attr('aria-selected', ((!isPanelSelected).toString()));

                // Toggle the panel's icon
                currHeader.children('.ui-icon').toggleClass('ui-icon-triangle-1-e', isPanelSelected).toggleClass('ui-icon-triangle-1-s', !isPanelSelected);

                // Toggle the panel's content
                currContent.toggleClass('accordion-content-active', !isPanelSelected)
                if (isPanelSelected) { currContent.slideUp(); } else { currContent.slideDown(); }

                return false; // Cancel the default action
            }
        });
    });
</script>

EPAM/EPAM.WebClient/Views/Author/MyJobs.cshtml
@{
    ViewBag.Title = "MyJobs";
    ViewBag.Menu = 0;
    ViewBag.Menu2 = 2;

    int num = 0;
}

@section Links{
    @Styles.Render("~/Content/Author/MyJobs.css")
}

@section FirstMenuBar{
    @Html.Partial("FirstMenuBar")
}

@section SecondMenuBar{
    @Html.Partial("JobsMenuBar")
}

<div id="accordion">
    <h1>Ongoing Jobs</h1>
    <div>
        @if (ViewBag.HasOngoingJobs)
        {
            foreach (EPAM.Model.Job item in ViewBag.OngoingJobs)
            {
                <div id="jobPost@(num)">
                    <div id="info">
                        <input type="hidden" name="jobId" value="@item.Id" />
                        @Html.ActionLink(item.Title, "JobOverview", "Author", new { jobId = item.Id }, null)
                        <h5>@item.ShortDescription<br />
                        Job category - @item.JobCategory.Name, Job subcategory - @item.JobSubcategory.Name
                        Posted date - @item.PostedDate, Deadline - @item.Deadline
                        Budget - @item.Budget$</h5>
                    </div>
                    <div id="submitButton">
                        <input type="button" value="Submit" />
                    </div>
                </div>
                num++;
            }
        }
        else
        {
            <h3>No Ongoing Jobs</h3>
        }
    </div>
    <h1>Past Jobs</h1>
    <div>
        @if (ViewBag.HasPastJobs)
        {
            foreach (EPAM.Model.Job item in ViewBag.PastJobs)
            {
                <div id="jobPost">
                    <div id="info">
                        <input type="hidden" name="jobId" value="@item.Id" />
                        @Html.ActionLink(item.Title, "JobOverview", "Author", new { jobId = item.Id }, null)
                        <h5>@item.ShortDescription<br />
                        Job category - @item.JobCategory.Name, Job subcategory - @item.JobSubcategory.Name
                        Posted date - @item.PostedDate, Deadline - @item.Deadline
                        Budget - @item.Budget$</h5>
                    </div>
                </div>
            }
        }
        else
        {
            <h3>No Past Jobs</h3>
        }
    </div>
</div>

<script>
    $(function () {
        //Accordion
        $('#accordion').accordion({
            collapsible: true,
            heightStyle: "content",

            beforeActivate: function (event, ui) {
                // The accordion believes a panel is being opened
                if (ui.newHeader[0]) {
                    var currHeader = ui.newHeader;
                    var currContent = currHeader.next('.ui-accordion-content');
                    // The accordion believes a panel is being closed
                } else {
                    var currHeader = ui.oldHeader;
                    var currContent = currHeader.next('.ui-accordion-content');
                }
                // Since we've changed the default behavior, this detects the actual status
                var isPanelSelected = currHeader.attr('aria-selected') == 'true';

                // Toggle the panel's header
                currHeader.toggleClass('ui-corner-all', isPanelSelected).toggleClass('accordion-header-active ui-state-active ui-corner-top', !isPanelSelected).attr('aria-selected', ((!isPanelSelected).toString()));

                // Toggle the panel's icon
                currHeader.children('.ui-icon').toggleClass('ui-icon-triangle-1-e', isPanelSelected).toggleClass('ui-icon-triangle-1-s', !isPanelSelected);

                // Toggle the panel's content
                currContent.toggleClass('accordion-content-active', !isPanelSelected)
                if (isPanelSelected) { currContent.slideUp(); } else { currContent.slideDown(); }

                return false; // Cancel the default action
            }
        });

        //Submit job
        $('div[id^="jobPost"]').each(function () {
            var id = $(this).find('#info > input').val();

            $(this).find('#submitButton > input').click(function () {
                $.ajax({
                    url: '@Url.Action("SubmitJob")',
                    data: { jobId: id },
                    type: 'POST',
                    success: function () {
                        location = "/Author/MyJobs";
                    }
                });
            });
        });
    });
</script>

EPAM/EPAM.WebClient/Views/Author/Talks.cshtml
@{
    ViewBag.Title = "Talks";
    ViewBag.Menu = 1;
}

@section FirstMenuBar{
    @Html.Partial("FirstMenuBar")
}

<h2>Talks - @Session["PersonId"]</h2>

EPAM/EPAM.WebClient/Views/Author/_JobPost.cshtml
@model EPAM.Model.Job

@{
    TimeSpan posted = DateTime.Now - Model.PostedDate;
    String postedString = "";
    if (posted.TotalMinutes < 60)
    {
        postedString = posted.Minutes + " minutes";
    }
    else if (posted.TotalHours < 24)
    {
        postedString = posted.Hours + " hours";
    }
    else
    {
        postedString = posted.Days + " days";
    }
}

<div id="jobPost@(ViewBag.Num)">
    <div id="info">
        <input type="hidden" name="jobId" value="@Model.Id" />
        @Html.ActionLink(Model.Title, "JobOverview", "Author", new { jobId = Model.Id }, null)
        <h4>Posted @postedString ago</h4>
        <h5>@Model.ShortDescription<br />
            Job category - @Model.JobCategory.Name, Job subcategory - @Model.JobSubcategory.Name
            Posted date - @Model.PostedDate, Deadline - @Model.Deadline
            Budget - @Model.Budget$
        </h5>
    </div>
    <div id="saveButton">
        <input type="button" value="Save" class="@(@Model.IsSavedByAuthorId((Guid)Session["PersonId"]) ? "pressed" : "")" />
    </div>
</div>

EPAM/EPAM.WebClient/Views/Author/_JobSubcategory.cshtml
@{
    if (ViewBag.HasItems == null)
    {
        ViewBag.HasItems = false;        
    }
    if (ViewBag.JobSubcategories == null)
    {
        ViewBag.JobSubcategories = new List<Object>();            
    }
}

@if (ViewBag.HasItems)
{
    <select id="subcategories" name="JobSubcategoryId"
            @if (!ViewBag.HasItems) { @: disabled
                        }>
        <option value="@Guid.Empty">Job subcategory</option>
        @foreach (var item in ViewBag.JobSubcategories)
        {
            <option value="@item.Id">@item.Name</option>
        }
    </select>
}