EPAM/EPAM.WebClient/Controllers/ClientController.cs
using EPAM.Model;
using EPAM.Model.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace EPAM.WebClient.Controllers
{
    public class ClientController : Controller
    {
        #region CreateJob
        public ActionResult CreateJob()
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            ViewBag.JobCategories = JobCategoryRepository.Instance.GetAllItems().OrderBy(i => i.Name);
            ViewBag.Questions = QuestionRepository.Instance.GetAllDefaultQuestions().OrderBy(i => i.Text);
            ViewBag.Skills = SkillRepository.Instance.GetAllItems().OrderBy(i => i.Title);
            return View();
        }

        [HttpPost]
        public PartialViewResult GetJobSubcategories(Guid JobCategoryId)
        {
            if (Session["PersonId"] == null)
                return null;

            List<JobSubcategory> jobSubcategories = JobSubcategoryRepository.Instance.GetCategorySubcategories(JobCategoryRepository.Instance.GetItemById(JobCategoryId));
            ViewBag.JobSubcategories = jobSubcategories.OrderBy(i => i.Name);
            ViewBag.HasItems = jobSubcategories.Count > 0;
            return PartialView("_JobSubcategory");
        }

        [HttpPost]
        public String GetQuestionTemplate()
        {
            if (Session["PersonId"] == null)
                return "";

            ViewBag.Questions = QuestionRepository.Instance.GetAllDefaultQuestions().OrderBy(i => i.Text);
            ViewBag.Num = 0;
            string t = ControllersLibrary.RenderPartialToString("~/Views/Client/_CreateQuestion.cshtml", this.ControllerContext, ViewData, TempData);
            return t;
        }

        [HttpPost]
        public String CreateJob(Job job, List<Question> questions, List<Guid> skillIds)
        {
            if (Session["PersonId"] == null || questions.Count > 5)
                return "";

            job.ClientId = (Guid)Session["PersonId"];
            job.PostedDate = DateTime.Now;
            if (JobRepository.Instance.SetItem(job))
            {
                foreach(var item in questions)
                {
                    item.Job = job;
                    QuestionRepository.Instance.SetItem(item);
                }
                foreach(var id in skillIds)
                {
                    JobSkill js = new JobSkill();
                    js.Job = job;
                    js.SkillId = id;
                    JobSkillRepository.Instance.SetItem(js);
                }
                return "/Client/PostedJobs";
            }
            return "";
        }
        #endregion

        #region PostedJobs
        public ActionResult PostedJobs()
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            Client client = ClientRepository.Instance.GetItemById((Guid)Session["PersonId"]);
            ViewBag.Jobs = JobRepository.Instance.GetClientOngoingJobs(client).Where(i => i.Author == null).OrderByDescending(i => i.PostedDate);
            ViewBag.HasJobs = Enumerable.Count(ViewBag.Jobs) > 0;

            return View();
        }
        #endregion

        #region ApplicationOverview
        public ActionResult ApplicationOverview(Guid applicationId)
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            return View(ApplicationRepository.Instance.GetItemById(applicationId));
        }

        public bool ApproveApplication(Guid applicationId)
        {
            Application application = ApplicationRepository.Instance.GetItemById(applicationId);
            application.IsApproved = true;
            ApplicationRepository.Instance.UpdateItem(application);

            Job job = application.Job;
            job.AuthorId = application.AuthorId;
            JobRepository.Instance.UpdateItem(job);

            foreach (var item in application.Job.Applications)
            {
                item.IsClosed = true;
                ApplicationRepository.Instance.UpdateItem(item);
            }

            return true;
        }

        public bool DeclineApplication(Guid applicationId)
        {
            Application application = ApplicationRepository.Instance.GetItemById(applicationId);
            application.IsClosed = true;
            ApplicationRepository.Instance.UpdateItem(application);

            return true;
        }
        #endregion

        #region JobOverview
        public ActionResult JobOverview(Guid jobId)
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            return View(JobRepository.Instance.GetItemById(jobId));
        }
        #endregion

        #region MyJobs
        public ActionResult MyJobs()
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            Client client = ClientRepository.Instance.GetItemById((Guid)Session["PersonId"]);
            ViewBag.OngoingJobs = JobRepository.Instance.GetClientOngoingJobs(client).Where(i => i.Author != null).OrderByDescending(i => i.PostedDate);
            ViewBag.HasOngoingJobs = Enumerable.Count(ViewBag.OngoingJobs) > 0;

            ViewBag.PastJobs = JobRepository.Instance.GetClientPastJobs(client);
            ViewBag.HasPastJobs = Enumerable.Count(ViewBag.PastJobs) > 0;

            return View();
        }
        #endregion

        #region AuthorOverview
        public ActionResult AuthorOverview(Guid authorId)
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            return View(AuthorRepository.Instance.GetItemById(authorId));
        }
        #endregion

        #region FindAuthors
        public void InitAuthorsPartial(List<Guid> authorIds, int page)
        {
            if (authorIds.Count == 0)
                ViewBag.HasAuthors = false;
            else
            {
                ViewBag.HasAuthors = true;

                ViewBag.Pages = new List<int>();
                for (int i = 0; i < (int)Math.Ceiling(authorIds.Count / 10.0); i++)
                {
                    ViewBag.Pages.Add(i + 1);
                }
                ViewBag.CurrentPage = page;
                ViewBag.Authors = new List<Author>();
                for (int i = (page - 1) * 10; i < page * 10 && i < authorIds.Count; i++)
                {
                    ViewBag.Authors.Add(AuthorRepository.Instance.GetItemById(authorIds[i]));
                }
            }
        }

        public ActionResult FindAuthors()
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            ViewBag.Skills = SkillRepository.Instance.GetAllItems().OrderBy(i => i.Title);
            AuthorFilter af = new AuthorFilter();
            List<Guid> authorIds = AuthorRepository.Instance.GetFilterAuthorIdsDirectly(af);
            InitAuthorsPartial(authorIds, 1);

            return View(af);
        }

        [HttpPost]
        public PartialViewResult GetAuthorsByFilter(AuthorFilter authorFilter, int page = 1)
        {
            if (Session["PersonId"] == null)
                return null;

            List<Guid> authorIds = AuthorRepository.Instance.GetFilterAuthorIdsDirectly(authorFilter);
            InitAuthorsPartial(authorIds, page);

            return PartialView("_Authors", authorFilter);
        }

        [HttpPost]
        public void SaveAuthor(Guid authorId)
        {
            ClientSavedAuthor csa = new ClientSavedAuthor();
            csa.ClientId = (Guid)Session["PersonId"];
            csa.AuthorId = authorId;
            ClientSavedAuthorRepository.Instance.SetItem(csa);
        }

        [HttpPost]
        public void UnSaveAuthor(Guid authorId)
        {
            Client client = ClientRepository.Instance.GetItemById((Guid)Session["PersonId"]);
            List<ClientSavedAuthor> list = ClientSavedAuthorRepository.Instance.GetClientSavedAuthors(client);
            foreach (var item in list)
                if (item.AuthorId.Equals(authorId))
                    ClientSavedAuthorRepository.Instance.RemoveItem(item);
        }
        #endregion

        #region SavedAuthors
        public ActionResult SavedAuthors()
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            Client client = ClientRepository.Instance.GetItemById((Guid)Session["PersonId"]);
            ViewBag.Authors = AuthorRepository.Instance.GetClientSavedAuthors(client);
            ViewBag.HasAuthors = Enumerable.Count(ViewBag.Authors) > 0;

            return View();
        }
        #endregion

        #region MyAuthors
        public ActionResult MyAuthors()
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            Client client = ClientRepository.Instance.GetItemById((Guid)Session["PersonId"]);

            ViewBag.OngoingAuthors = JobRepository.Instance.GetClientOngoingJobs(client).Where(i => i.Author != null).Select(i => i.Author).Distinct();
            ViewBag.HasOngoingAuthors = Enumerable.Count(ViewBag.OngoingAuthors) > 0;

            ViewBag.PastAuthors = JobRepository.Instance.GetClientPastJobs(client).Select(i => i.Author).Distinct();
            ViewBag.HasPastAuthors = Enumerable.Count(ViewBag.PastAuthors) > 0;

            return View();
        }
        #endregion

        #region Talks
        public ActionResult Talks()
        {
            if (Session["PersonId"] == null)
                return Redirect(ControllersLibrary.LogInPage);

            return View();
        }
        #endregion

        #region Profile

EPAM/EPAM.WebClient/Controllers/SignUpController.cs
using EPAM.Model;
using EPAM.Model.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EPAM.WebClient.Controllers
{
    public class SignUpController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Client()
        {
            ViewBag.TimeZones = TimeZoneRepository.Instance.GetAllItems().OrderBy(i => i.Title);
            return View();
        }

        public ActionResult Author()
        {
            ViewBag.TimeZones = TimeZoneRepository.Instance.GetAllItems().OrderBy(i => i.Title);
            return View();
        }

        [HttpPost]
        public String RegisterAuthor(Author a, String repassword)
        {
            return Register(a, repassword);
        }

        [HttpPost]
        public String RegisterClient(Client c, String repassword)
        {
            return Register(c, repassword);
        }

        private String Register(Person p, String repassword)
        {
            if (p.Password == repassword && PersonRepository.Instance.Register(p))
                return "/Login/Index";
            return "";
        }
    }
}

EPAM/EPAM.WebClient/Views/SignUp/Author.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSignUp.cshtml";
    ViewBag.Title = "Author";
    ViewBag.CSS = Url.Content("~/Content/SignUp/Author.css");
}

<div id="content-title">Create a Free Author Account</div>
Looking to hire? @Html.ActionLink("Sign up as a client", "Client", "SignUp")<br><br>
<form id="form" method="post" action="~/SignUp/RegisterAuthor">
    <div id="fields">
        <input type="text" name="Name" placeholder="First Name" />
        <input type="text" name="SName" placeholder="Last Name" />
        <input type="text" name="Email" placeholder="Email" />
        <select name="TimeZoneId">
            <option value="@Guid.Empty">TimeZone</option>
            @foreach (var item in ViewBag.TimeZones)
            {
                <option value="@item.Id">@item.Title</option>
            }
        </select>
        <input name="Login" value="" placeholder="Login" />
        <input name="Password" type="password" value="" placeholder="Password" id="Password" />
        <input name="repassword" type="password" value="" placeholder="Repeat Password" />
    </div>
    <div id="button"><input type="submit" class="button" value="Get Started" /></div>
    <label id="error" class="hidden">Error occurred while registration</label>
</form>

<script>
    $(function () {
        jQuery.validator.addMethod(
            "regexp",
            function (value, element, regexp) {
                var re = new RegExp(regexp);
                return this.optional(element) || re.test(value);
            });

        jQuery.validator.addMethod(
            "notEqual",
            function (value, element, param) {
                return this.optional(element) || value !== param;
            });

        $('#form').validate({
            rules: {
                Name: {
                    required: true,
                    regexp: /^[a-zA-Z]{3,20}$/
                },
                SName: {
                    required: true,
                    regexp: /^[a-zA-Z]{3,20}$/
                },
                Email: {
                    required: true,
                    regexp: /^[0-9a-zA-Z_.]+@@[0-9a-zA-Z.-]+.[a-zA-Z]{2,4}$/
                },
                TimeZoneId: {
                    notEqual: '00000000-0000-0000-0000-000000000000'
                },
                Login: {
                    required: true,
                    regexp: /^[a-zA-Z0-9]{5,20}$/
                },
                Password: {
                    required: true,
                    regexp: /^[a-zA-Z0-9]{5,20}$/
                },
                repassword: {
                    required: true,
                    equalTo: '#Password'
                }
            },
            messages: {
                Name: {
                    required: "First name is required",
                    regexp: "First name must consist only of 3 to 20 latin letters"
                },
                SName: {
                    required: "Last name is required",
                    regexp: "Last name must consist only of 3 to 20 latin letters"
                },
                Email: {
                    required: "Email is required",
                    regexp: "Incorrect email"
                },
                TimeZoneId: {
                    notEqual: "TimeZone is required"
                },
                Login: {
                    required: "Login is required",
                    regexp: "Login must consist only of 5 to 20 latin letters or numbers"
                },
                Password: {
                    required: "Password is required",
                    regexp: "Password must consist only of 5 to 20 latin letters or numbers"
                },
                repassword: {
                    required: "Repassword is required",
                    equalTo: "Repeat password correctly"
                }
            },
            submitHandler: function (form) {
                var postData = $(form).serializeArray();
                var formURL = $(form).attr("action");
                $.ajax({
                    url: formURL,
                    data: postData,
                    type: 'POST',
                    success: function (data) {
                        if (data == '')
                            $('#error').removeClass('hidden');
                        else
                            location = data;
                    }
                });
            }
        });
    });
</script>

EPAM/EPAM.WebClient/Views/SignUp/Client.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSignUp.cshtml";
    ViewBag.Title = "Client";
    ViewBag.CSS = Url.Content("~/Content/SignUp/Client.css");
}

<div id="content-title">Create a Free Client Account</div>
Looking for work? @Html.ActionLink("Sign up as a author", "Author", "SignUp")<br><br>
<form id="form" method="post" action="~/SignUp/RegisterClient">
    <div id="IsCompany">
        <input type="radio" name="IsCompany" value="true" checked="checked" />Company Sing Up&nbsp;&nbsp;&nbsp;
        <input type="radio" name="IsCompany" value="false" />Individual Sign Up
    </div>
    <div id="fields">
        <input type="text" name="Name" placeholder="First Name" />
        <input type="text" name="SName" placeholder="Last Name" />
        <input type="text" name="Email" placeholder="Email" />
        <input type="text" name="CompanyName" placeholder="CompanyName" />
        <select name="TimeZoneId">
            <option value="@Guid.Empty">TimeZone</option>
            @foreach (var item in ViewBag.TimeZones)
            {
                <option value="@item.Id">@item.Title</option>
            }
        </select>
        <input name="Login" value="" placeholder="Login" />
        <input id="Password" name="Password" type="password" value="" placeholder="Password" />
        <input name="repassword" type="password" value="" placeholder="Repeat Password" />
    </div>
    <div id="button"><input type="submit" class="button" value="Get Started" /></div>
    <label id="error" class="hidden">Error occurred while registration</label>
</form>

<script>
    $(function () {
        $('input[name="IsCompany"]').change(function () {
            if ($(this).val() === "true") {
                $('input[name="CompanyName"]').removeClass("hidden");
                $('label[for="CompanyName"]').removeClass("hidden");
            }
            else {
                $('input[name="CompanyName"]').addClass("hidden");
                $('label[for="CompanyName"]').addClass("hidden");
            }
        });

        jQuery.validator.addMethod(
            "regexp",
            function (value, element, regexp) {
                var re = new RegExp(regexp);
                return this.optional(element) || re.test(value);
            });

        jQuery.validator.addMethod(
            "notEqual",
            function (value, element, param) {
                return this.optional(element) || value !== param;
            });

        $('#form').validate({
            rules: {
                Name: {
                    required: true,
                    regexp: /^[a-zA-Z]{3,20}$/
                },
                SName: {
                    required: true,
                    regexp: /^[a-zA-Z]{3,20}$/
                },
                CompanyName: {
                    required: 'input[name="IsCompany"]:checked',
                    regexp: /^[a-zA-Z]{3,30}$/
                },
                Email: {
                    required: true,
                    regexp: /^[0-9a-zA-Z_.]+@@[0-9a-zA-Z.-]+.[a-zA-Z]{2,4}$/
                },
                TimeZoneId: {
                    notEqual: '00000000-0000-0000-0000-000000000000'
                },
                Login: {
                    required: true,
                    regexp: /^[a-zA-Z0-9]{5,20}$/
                },
                Password: {
                    required: true,
                    regexp: /^[a-zA-Z0-9]{5,20}$/
                },
                repassword: {
                    required: true,
                    equalTo: '#Password'
                }
            },
            messages: {
                Name: {
                    required: "First name is required",
                    regexp: "First name must consist only of 3 to 20 latin letters"
                },
                SName: {
                    required: "Last name is required",
                    regexp: "Last name must consist only of 3 to 20 latin letters"
                },
                CompanyName: {
                    required: "Company name is required",
                    regexp: "Company name must consist only of 3 to 30 latin letters"
                },
                Email: {
                    required: "Email is required",
                    regexp: "Incorrect email"
                },
                TimeZoneId: {
                    notEqual: "TimeZone is required"
                },
                Login: {
                    required: "Login is required",
                    regexp: "Login must consist only of 5 to 20 latin letters or numbers"
                },
                Password: {
                    required: "Password is required",
                    regexp: "Password must consist only of 5 to 20 latin letters or numbers"
                },
                repassword: {
                    required: "Repassword is required",
                    equalTo: "Repeat password correctly"
                }
            },
            submitHandler: function (form) {
                var postData = $(form).serializeArray();
                var formURL = $(form).attr("action");
                $.ajax({
                    url: formURL,
                    data: postData,
                    type: 'POST',
                    success: function (data) {
                        if (data == '')
                            $('#error').removeClass('hidden');
                        else
                            location = data;
                    }
                });
            }
        });
    });
</script>

EPAM/EPAM.WebClient/Views/SignUp/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSignUp.cshtml";
    ViewBag.Title = "Sign Up";
    ViewBag.CSS = Url.Content("~/Content/SignUp/Index.css");
}

<div id="content-title">
    Let's get started!<br>
    First, tell us what you're looking for.
</div>
<div id="left-center">
    <div id="left">
        <a title="Client"><img src="/Content/Images/client.png" width="100" height="100" alt="" /></a>
        <div class="big">I want to hire a freelancer<br><br></div>
        <div class="small">Find, collaborate with, and pay an expert.</div>
        <div class="button">@Html.ActionLink("Hire", "Client", "SignUp", null, new { @class = "button" })</div>
    </div>
    <div id="center">
        <div class="verticalLine"></div>
        <div class="big">OR</div>
        <div class="verticalLine"></div>
    </div>
</div>
<div id="right">
    <a title="Author"><img src="/Content/Images/author.png" width="100" height="100" alt="" /></a>
    <div class="big">I'm looking for online work<br><br></div>
    <div class="small">Find freelance projects and grow your business.</div>
    <div class="button">@Html.ActionLink("Work", "Author", "SignUp", null, new { @class = "button" })</div>
</div>